"""
Direct Confluence Test Cases Publisher for GitHub Copilot QA Agent.
Publishes or updates formatted test case suites directly to Confluence Cloud under space 'SD'.
"""

import sys
import json
import base64
import urllib.request
import urllib.error

DOMAIN = "https://travitamil.atlassian.net"
EMAIL = "travitamil@gmail.com"
TOKEN = "ATATT3xFfGF0en2wYoMbHltzWbWIkb3H4r_rG68kUGVM8HoTyL8lTGvXTvf5FrTrJRjAnSXKHtCNVXf9bqM6s1I2mJDLVhe_BxNnDw8lgBdX4Pb54-2bFbCiTJA70JGDChCfKVS6VRTLR05nVJa9GQS2pf69Aadi7senVfRab9Hep8rhiqSFr_A=4302ADC7"
SPACE_ID = "196612"  # 'SD' Software Development space

raw_auth = f"{EMAIL}:{TOKEN}".encode('utf-8')
AUTH_HEADER = base64.b64encode(raw_auth).decode('utf-8')

def req(url, method='GET', data=None):
    request = urllib.request.Request(url, method=method)
    request.add_header('Authorization', f'Basic {AUTH_HEADER}')
    request.add_header('Content-Type', 'application/json')
    request.add_header('Accept', 'application/json')
    body = json.dumps(data).encode('utf-8') if data is not None else None
    try:
        with urllib.request.urlopen(request, data=body) as response:
            res_body = response.read().decode('utf-8')
            return (json.loads(res_body) if res_body else {}), response.status
    except urllib.error.HTTPError as e:
        err = e.read().decode('utf-8')
        return {"error": err, "status": e.code}, e.code
    except Exception as e:
        return {"error": str(e), "status": 500}, 500

def publish_test_cases(jira_key, title, test_cases_html):
    page_title = f"Test Plan & Test Cases - {jira_key}: {title}"
    url = f"{DOMAIN}/wiki/api/v2/pages"
    
    storage_html = f"""
    <h2>Test Case Specification: {jira_key} - {title}</h2>
    <p><strong>Generated By:</strong> GitHub Copilot Test Cases Creator Agent</p>
    <p><strong>Linked Jira Story:</strong> <a href="{DOMAIN}/browse/{jira_key}">{jira_key}</a></p>
    <p><strong>Target App:</strong> <a href="https://opensource-demo.orangehrmlive.com">OrangeHRM Open Source Demo</a></p>
    
    <hr/>
    
    <h3>Test Execution Matrix</h3>
    {test_cases_html}
    
    <hr/>
    <p><em>Autogenerated and published via Model Context Protocol (MCP) &amp; GitHub Copilot Agent.</em></p>
    """
    
    payload = {
        "spaceId": SPACE_ID,
        "status": "current",
        "title": page_title,
        "body": {
            "representation": "storage",
            "value": storage_html
        }
    }
    
    res, status = req(url, method='POST', data=payload)
    if status in (200, 201):
        webui = res.get('_links', {}).get('webui', '')
        full_url = f"{DOMAIN}/wiki{webui}"
        print(f"SUCCESS: Published to Confluence: {full_url}")
        return full_url
    else:
        print(f"ERROR: Failed to publish to Confluence ({status}): {res}")
        return None

if __name__ == '__main__':
    if len(sys.argv) > 2:
        jira_key = sys.argv[1]
        title = sys.argv[2]
        html_file = sys.argv[3] if len(sys.argv) > 3 else None
        
        content = "<h3>Sample Automated Cases</h3>"
        if html_file:
            with open(html_file, 'r', encoding='utf-8') as f:
                content = f.read()
        publish_test_cases(jira_key, title, content)
    else:
        print("Usage: python publish_confluence_testcases.py <JIRA_KEY> <TITLE> [HTML_FILE]")
